# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

repos:
  CRAN: http://cran.rstudio.com

bioc_packages:
 - RTCGA.rnaseq

r:
  - oldrel
  - release
  - devel

after_success:
  - Rscript -e 'covr::codecov()'
